--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AIPTU/BlockReplacer
branches:
- master
projects:
  BlockReplacer:
    path: ""
    icon: "icon.png"
    libs:
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
      - src: DiamondStrider1/Sounds/Sounds
        version: ^1.2.2
...
