--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AIPTU/BlockReplacer
branches:
- master
- dev
projects:
  BlockReplacer:
    path: ""
    icon: "icon.png"
    libs:
      UpdateNotifier:
        src: ifera-mc/UpdateNotifier/UpdateNotifier
        branch: "API-4.0.0"
        version: ^2.2.0
...
