---
name: BlockReplacer
main: aiptu\blockreplacer\BlockReplacer
version: 1.2.0
api: [3.24.0]
author: AIPTU
permissions:
  blockreplacer.bypass:
    default: op
    description: Allows users to bypass block replacement.
...